<a href="https://colab.research.google.com/github/poorveegautam/colab/blob/main/Copy_of_ML_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

In [ ]:
df = pd.read_csv('/content/workout_dataset - Sheet2.csv')
df.head()

Gender   BMI  Age  Calorie intake      Exercise  Set
0  Female  22.0   32              99  Barbell Rows    3
1  Female  26.0   30              91  Barbell Rows    3
2    Male  23.5   26             147   Bench Press    3
3    Male  23.5   22             145   Bench Press    3
4    Male  21.0   29             146   Bench Press    3

In [ ]:
# Load and preprocess the dataset

X = df[['Gender','BMI', 'Calorie intake','Age']]
y = df[['Exercise', 'Set']]


In [ ]:
les = LabelEncoder()
y['Exercise'] = les.fit_transform(y['Exercise'])

<ipython-input-54-9078a6250cfd>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Exercise'] = les.fit_transform(y['Exercise'])


In [ ]:
les.classes_

array(['Barbell Rows', 'Bench Press', 'Bicep Curls', 'Bicycle Crunches',
       'Cable Tricep Pushdown', 'Calf Raises', 'Chin-ups',
       'Close Grip Bench Press', 'Deadlift', 'Dumbbell Rows',
       'Dumbbell Shoulder Press', 'Dumbbell Tricep Extension',
       'Incline Bench Press', 'Incline Dumbbell Bench Press',
       'Lat Pulldown', 'Leg Press', 'Lunges', 'Overhead Press', 'Plank',
       'Pull-ups', 'Squat', 'Sun Salutation', 'T-Bar Rows',
       'Treadmill Running', 'Tricep Dips', 'Tricep Kickbacks',
       'Tricep Rope Pushdowns', 'Warrior II'], dtype=object)

In [ ]:
y

Exercise  Set
0          0    3
1          0    3
2          1    3
3          1    3
4          1    3
..       ...  ...
61        25    2
62        26    2
63        27    1
64        27    1
65        27    1

[66 rows x 2 columns]

In [ ]:
le = LabelEncoder()
X['Gender'] = le.fit_transform(X['Gender'])
X

<ipython-input-59-8dcb0150d395>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Gender'] = le.fit_transform(X['Gender'])


Gender   BMI  Calorie intake  Age
0        0  22.0              99   32
1        0  26.0              91   30
2        1  23.5             147   26
3        1  23.5             145   22
4        1  21.0             146   29
..     ...   ...             ...  ...
61       0  22.1              90   31
62       0  20.8              90   32
63       0  22.0             187   26
64       0  21.0             187   27
65       0  20.0             187   29

[66 rows x 4 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2, random_state=42)


X_train.values.tolist()


[[1.0, 26.8, 69.0, 28.0],
 [1.0, 23.1, 100.0, 35.0],
 [1.0, 23.5, 145.0, 22.0],
 [1.0, 25.0, 97.0, 44.0],
 [0.0, 21.6, 162.0, 29.0],
 [0.0, 25.0, 132.0, 28.0],
 [0.0, 24.0, 43.0, 27.0],
 [0.0, 22.5, 120.0, 30.0],
 [1.0, 21.0, 146.0, 29.0],
 [0.0, 21.0, 60.0, 26.0],
 [1.0, 26.8, 69.0, 28.0],
 [1.0, 23.9, 140.0, 27.0],
 [1.0, 26.0, 128.0, 37.0],
 [1.0, 26.0, 180.0, 37.0],
 [1.0, 24.0, 182.0, 32.0],
 [1.0, 25.8, 156.0, 40.0],
 [0.0, 24.9, 127.0, 35.0],
 [1.0, 26.1, 102.0, 35.0],
 [0.0, 21.0, 187.0, 27.0],
 [1.0, 22.5, 110.0, 28.0],
 [1.0, 24.6, 78.0, 29.0],
 [1.0, 24.6, 78.0, 29.0],
 [1.0, 25.5, 80.0, 30.0],
 [0.0, 24.0, 60.0, 24.0],
 [1.0, 23.1, 100.0, 35.0],
 [0.0, 25.0, 140.0, 33.0],
 [0.0, 22.1, 90.0, 31.0],
 [0.0, 23.0, 66.0, 22.0],
 [1.0, 23.7, 53.0, 32.0],
 [0.0, 22.5, 120.0, 30.0],
 [0.0, 21.6, 162.0, 29.0],
 [1.0, 24.5, 130.0, 32.0],
 [0.0, 26.0, 91.0, 30.0],
 [0.0, 25.4, 116.0, 28.0],
 [1.0, 23.5, 147.0, 26.0],
 [1.0, 27.2, 140.0, 31.0],
 [1.0, 22.0, 52.0, 34.0],
 [1.0, 27.0, 70

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[ 0.82305489,  1.28809775, -1.15891667, -0.63061087],
       [ 0.82305489, -0.65262275, -0.36191425,  0.74389426],
       [ 0.82305489, -0.44281512,  0.79502475, -1.80875814],
       [ 0.82305489,  0.34396346, -0.43904352,  2.51111516],
       [-1.21498579, -1.43940133,  1.23209059, -0.434253  ],
       [-1.21498579,  0.34396346,  0.46079792, -0.63061087],
       [-1.21498579, -0.1805556 , -1.82737031, -0.82696875],
       [-1.21498579, -0.96733418,  0.15228086, -0.23789512],
       [ 0.82305489, -1.75411276,  0.8207345 , -0.434253  ],
       [-1.21498579, -1.75411276, -1.39030447, -1.02332663],
       [ 0.82305489,  1.28809775, -1.15891667, -0.63061087],
       [ 0.82305489, -0.2330075 ,  0.66647597, -0.82696875],
       [ 0.82305489,  0.86848251,  0.3579589 ,  1.13661002],
       [ 0.82305489,  0.86848251,  1.69486619,  1.13661002],
       [ 0.82305489, -0.1805556 ,  1.7462857 ,  0.15482063],
       [ 0.82305489,  0.7635787 ,  1.07783206,  1.72568365],
       [-1.21498579,  0.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.multioutput import MultiOutputClassifier

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



# Train the MLP classification model for predicting both exercise and sets
model = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)


model.fit(X_train,y_train["Exercise"])
# model.fit(X_train,y_train["Set"])

# multi_model = MultiOutputClassifier(model)
# multi_model.fit(X_train, y_train)




MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.multioutput import MultiOutputClassifier

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



# Train the MLP classification model for predicting both exercise and sets
modelSet = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)


# model.fit(X_train,y_train["Exercise"])
modelSet.fit(X_train,y_train["Set"])

# multi_model = MultiOutputClassifier(model)
# multi_model.fit(X_train, y_train)


MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)

In [ ]:
print(X_train)

[[ 0.82305489  1.28809775 -1.15891667 -0.63061087]
 [ 0.82305489 -0.65262275 -0.36191425  0.74389426]
 [ 0.82305489 -0.44281512  0.79502475 -1.80875814]
 [ 0.82305489  0.34396346 -0.43904352  2.51111516]
 [-1.21498579 -1.43940133  1.23209059 -0.434253  ]
 [-1.21498579  0.34396346  0.46079792 -0.63061087]
 [-1.21498579 -0.1805556  -1.82737031 -0.82696875]
 [-1.21498579 -0.96733418  0.15228086 -0.23789512]
 [ 0.82305489 -1.75411276  0.8207345  -0.434253  ]
 [-1.21498579 -1.75411276 -1.39030447 -1.02332663]
 [ 0.82305489  1.28809775 -1.15891667 -0.63061087]
 [ 0.82305489 -0.2330075   0.66647597 -0.82696875]
 [ 0.82305489  0.86848251  0.3579589   1.13661002]
 [ 0.82305489  0.86848251  1.69486619  1.13661002]
 [ 0.82305489 -0.1805556   1.7462857   0.15482063]
 [ 0.82305489  0.7635787   1.07783206  1.72568365]
 [-1.21498579  0.29151155  0.33224915  0.74389426]
 [ 0.82305489  0.92093442 -0.31049474  0.74389426]
 [-1.21498579 -1.75411276  1.87483448 -0.82696875]
 [ 0.82305489 -0.96733418 -0.10

In [ ]:
pred_val = model.predict(scaler.transform([[1,	18.5,	302,30]]))
pred_val

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([27])

In [ ]:
!pip install sklite

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklite import LazyExport


lazy = LazyExport(model)

lazy.save('fitness.json')

In [ ]:
from sklite import LazyExport


lazy = LazyExport(modelSet)

lazy.save('fitnessSet.json')